### ISSUE TITLE
Dead system on pageload

### ISSUE THREAD

**Issue by unusualbob** [martindale/soundtrack.io#120]
Loaded up soundtrack and found nothing was playing and track time was NaN
![screen shot](https://cloud.githubusercontent.com/assets/739442/5662401/3dbe80a6-9741-11e4-91f0-47aea547b811.png)

console shows
```
angular updatePlaylist()
(index):28 GET https://soundtrack.io/js/underscore-min.map 404 (Not Found)
(index):33 GET https://soundtrack.io/js/angular.min.js.map 404 (Not Found)
angular.min.js:92 TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at https://soundtrack.io/js/app.js:233:10
    at https://soundtrack.io/js/angular.min.js:72:82
    at J (https://soundtrack.io/js/angular.min.js:100:187)
    at J (https://soundtrack.io/js/angular.min.js:100:187)
    at https://soundtrack.io/js/angular.min.js:101:350
    at h.$eval (https://soundtrack.io/js/angular.min.js:112:316)
    at h.$digest (https://soundtrack.io/js/angular.min.js:109:392)
    at h.$apply (https://soundtrack.io/js/angular.min.js:113:100)
    at g (https://soundtrack.io/js/angular.min.js:72:337)
app.js:337 player loaded. :)
app.js:140 setting volume to  0.8
app.js:221 angular updatePlaylist()
angular.min.js:92 TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at https://soundtrack.io/js/app.js:233:10
    at https://soundtrack.io/js/angular.min.js:72:82
    at J (https://soundtrack.io/js/angular.min.js:100:187)
    at J (https://soundtrack.io/js/angular.min.js:100:187)
    at https://soundtrack.io/js/angular.min.js:101:350
    at h.$eval (https://soundtrack.io/js/angular.min.js:112:316)
    at h.$digest (https://soundtrack.io/js/angular.min.js:109:392)
    at h.$apply (https://soundtrack.io/js/angular.min.js:113:100)
    at g (https://soundtrack.io/js/angular.min.js:72:337)
app.js:357 Object {type: "join", data: Object}
```

**Comment by martindale** [comment]
I can't replicate this, but it looks like somehow the "playlist" is empty.  I don't know when this would happen (there should always be a "currently playing" track).  Any ideas?
