### ISSUE TITLE
Coverage does not run

### ISSUE THREAD

**Issue by martindale** [martindale/soundtrack.io#154]
Currently, `mocha` will successfully run the tests, `_mocha` will _also_ successfully run the tests, but `istanbul cover _mocha` will fail with the following error:

```bash
$ istanbul cover _mocha


  1) "before all" hook

  0 passing (9ms)
  1 failing

  1)  "before all" hook:
     Uncaught Error: connect ECONNREFUSED
      at errnoException (net.js:905:11)
      at Object.afterConnect [as oncomplete] (net.js:896:19)
```

**Comment by martindale** [comment]
Closed in favor of martindale/maki#55.
