### ISSUE TITLE
ChangeTip is Broken

### ISSUE THREAD

**Issue by Bogie21** [martindale/soundtrack.io#180]
Trying to add Changetip to my account produces the following error: 

AuthorizationError
   at Strategy.OAuth2Strategy.authenticate (/home/eric/soundtrack.io/node_modules/passport-changetip/node_modules/passport-oauth2/lib/strategy.js:126:25)
   at Strategy.authenticate (/home/eric/soundtrack.io/node_modules/passport-changetip/lib/oauth2.js:21:41)
   at attempt (/home/eric/soundtrack.io/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
   at Passport.authenticate (/home/eric/soundtrack.io/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
   at Layer.handle [as handle_request] (/home/eric/soundtrack.io/node_modules/express/lib/router/layer.js:82:5)
   at next (/home/eric/soundtrack.io/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/home/eric/soundtrack.io/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/home/eric/soundtrack.io/node_modules/express/lib/router/layer.js:82:5)
   at /home/eric/soundtrack.io/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/home/eric/soundtrack.io/node_modules/express/lib/router/index.js:321:12)

I receive the same error when trying to tip as well.  

AuthorizationError
   at Strategy.OAuth2Strategy.authenticate (/home/eric/soundtrack.io/node_modules/passport-changetip/node_modules/passport-oauth2/lib/strategy.js:126:25)
   at Strategy.authenticate (/home/eric/soundtrack.io/node_modules/passport-changetip/lib/oauth2.js:21:41)
   at attempt (/home/eric/soundtrack.io/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
   at Passport.authenticate (/home/eric/soundtrack.io/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
   at Layer.handle [as handle_request] (/home/eric/soundtrack.io/node_modules/express/lib/router/layer.js:82:5)
   at next (/home/eric/soundtrack.io/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/home/eric/soundtrack.io/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/home/eric/soundtrack.io/node_modules/express/lib/router/layer.js:82:5)
   at /home/eric/soundtrack.io/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/home/eric/soundtrack.io/node_modules/express/lib/router/index.js:321:12)

**Comment by martindale** [comment]
I've disabled ChangeTip for now, I don't really have time to troubleshoot it right now.  I'll come back to this soon, though!
