### ISSUE TITLE
Creating a new soundtrack page without a description breaks that page

### ISSUE THREAD

**Issue by mobyvb** [martindale/soundtrack.io#198]
The error is here: https://github.com/martindale/soundtrack.io/blob/soundtrack.io/controllers/pages.js#L50

```
Cannot call method 'toString' of undefined
   at eval (eval at <anonymous> (/home/eric/soundtrack.io/node_modules/jade/lib/jade.js:164:8), <anonymous>:780:71)
   at /home/eric/soundtrack.io/node_modules/jade/lib/jade.js:165:35
   at Object.exports.render (/home/eric/soundtrack.io/node_modules/jade/lib/jade.js:199:14)
   at View.exports.renderFile [as engine] (/home/eric/soundtrack.io/node_modules/jade/lib/jade.js:226:13)
   at View.render (/home/eric/soundtrack.io/node_modules/express/lib/view.js:93:8)
   at EventEmitter.app.render (/home/eric/soundtrack.io/node_modules/express/lib/application.js:566:10)
   at ServerResponse.res.render (/home/eric/soundtrack.io/node_modules/express/lib/response.js:938:7)
   at /home/eric/soundtrack.io/controllers/pages.js:48:11
   at /home/eric/soundtrack.io/node_modules/async/lib/async.js:232:13
   at /home/eric/soundtrack.io/node_modules/async/lib/async.js:119:25 
```

I can try to  fix this later today if I have time.

**Comment by martindale** [comment]
This is resolved by f79127a.
