### ISSUE TITLE
Error on visit

### ISSUE THREAD

**Issue by lakario** [martindale/soundtrack.io#72]
I've seen the following error page twice upon visiting with old cookies. Deleting my cookies fixes the problem.

```
TypeError: /root/soundtrack.io/views/index.jade:113
    111|               for playlist in playlists
    112|                 li(data-playlist-id="#{playlist._id}")
  > 113|                   a(href="/#{user.slug}/#{playlist.slug}")
    114|                     small.pull-right #{playlist._tracks.length}
    115|                     input(type="checkbox", data-action="toggle-playlist-visibility", data-playlist-id="#{playlist._id}", checked=(playlist.public ? "checked" : undefined))
    116|                     |  #{playlist.name}

Cannot read property 'slug' of undefined
    at eval (eval at <anonymous> (/root/soundtrack.io/node_modules/jade/lib/jade.js:164:8))
    at eval (eval at <anonymous> (/root/soundtrack.io/node_modules/jade/lib/jade.js:164:8))
    at exports.compile (/root/soundtrack.io/node_modules/jade/lib/jade.js:165:35)
    at Object.exports.render (/root/soundtrack.io/node_modules/jade/lib/jade.js:199:14)
    at View.exports.renderFile [as engine] (/root/soundtrack.io/node_modules/jade/lib/jade.js:226:13)
    at View.render (/root/soundtrack.io/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/root/soundtrack.io/node_modules/express/lib/application.js:505:10)
    at ServerResponse.res.render (/root/soundtrack.io/node_modules/express/lib/response.js:756:7)
    at Promise.<anonymous> (/root/soundtrack.io/controllers/pages.js:9:13)
    at Promise.onResolve (/root/soundtrack.io/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
```

**Comment by martindale** [comment]
This should no longer be an issue.  Open a new one if you encounter something similar.
